#!/usr/bin/env python3
"""Emit dist/indicator.pine and dist/strategy.pine from pine/core.pine.

Line prefixes in core.pine:  "//$I " -> kept only in indicator build;  "//$S " -> kept only in strategy build.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(HERE, "..", "dist")
CORE = open(os.path.join(HERE, "core.pine"), encoding="utf-8").read()

IND_HEADER = '''//@version=6
// Risk-Averse FX Day Trader v1 — INDICATOR. Generated by pine/build.py from pine/core.pine. Do not edit here.
// Chart: 15m, symbol FX:EURUSD (or any FX:xxx / UTC-aligned feed). Rules: spec/rules_v1.md
indicator("Risk-Averse FX Day Trader v1", "RAFX v1", overlay=true, max_labels_count=500, max_lines_count=500, calc_bars_count=20000)
'''

STR_HEADER = '''//@version=6
// Risk-Averse FX Day Trader v1 — STRATEGY (for the built-in tester). Generated by pine/build.py from pine/core.pine.
// Note: the tester resolves same-bar SL+TP optimistically and has no spread; slippage below approximates spread+slippage.
// Python backtest (py/) is the source of truth for expectancy; use this for visual checks and the trade list export.
strategy("Risk-Averse FX Day Trader v1 [strategy]", "RAFX v1 S", overlay=true, initial_capital=10000, currency=currency.USD,
     default_qty_type=strategy.fixed, default_qty_value=10000, slippage=7, commission_type=strategy.commission.cash_per_contract,
     commission_value=0, process_orders_on_close=false, calc_on_every_tick=false, max_labels_count=500, max_lines_count=500,
     calc_bars_count=20000)
'''


def build(mode: str) -> str:
    out = []
    for line in CORE.splitlines():
        m = re.match(r"^(\s*)//\$([IS]) ?(.*)$", line)
        if m:
            indent, tag, rest = m.groups()
            if tag == mode:
                out.append(indent + rest)
            continue
        out.append(line)
    return (IND_HEADER if mode == "I" else STR_HEADER) + "\n".join(out) + "\n"


if __name__ == "__main__":
    os.makedirs(DIST, exist_ok=True)
    for mode, name in (("I", "indicator.pine"), ("S", "strategy.pine")):
        p = os.path.join(DIST, name)
        open(p, "w", encoding="utf-8").write(build(mode))
        print("wrote", os.path.relpath(p))
